name: NodeJS application deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/simple-nodejs-project

            git pull origin main

            docker build -t my-nodejs-app .

            docker stop my-nodejs-app-container || true
            docker rm my-nodejs-app-container || true

            docker run -d \
              -p 8000:8000 \
              --name my-nodejs-app-container \
              my-nodejs-app